name: 'Domloo Release Action'
description: 'Smart release automation using custom bot identities'

inputs:
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Run Security Guard Scanner
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/action-scripts/security-guard.sh"
        "${{ github.action_path }}/action-scripts/security-guard.sh"

    - name: Deteksi Trigger
      shell: bash
      env:
        RAW_COMMENT: ${{ github.event.comment.body }}
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/detect-trigger.sh
        bash ${{ github.action_path }}/action-scripts/detect-trigger.sh

    - name: Calculate Folder Hash
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/calculate-hash.sh
        bash ${{ github.action_path }}/action-scripts/calculate-hash.sh

    - name: Cache Domloo Dependencies & Dist
      id: domloo-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.action_path }}/node_modules
          ${{ github.action_path }}/dist
        key: domloo-build-${{ env.DOMLOO_SRC_HASH }}

    - name: Install & Compile On-the-Fly
      if: steps.domloo-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/install-compile.sh
        bash ${{ github.action_path }}/action-scripts/install-compile.sh

    - name: Jalankan Otak Bot Pinter
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Update File Konfigurasi Projek (SED Engine)
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/sed-engine.sh
        bash ${{ github.action_path }}/action-scripts/sed-engine.sh

    - name: Create Release Branch and Push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/push-engine.js