name: 'Domloo Release Action'
description: 'Smart release automation using custom bot identities'

inputs:
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite" # Ini pembedanya, ngasih tahu GitHub kalau ini composite
  steps:
    - name: Deteksi Trigger
      shell: bash # DI COMPOSITE WAJIB TULIS SHELL DI TIAP STEP RUN
      run: |
        if [ "${{ github.event_name }}" == "issue_comment" ]; then
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "COMMENT_FOUND=$COMMENT_BODY" >> $GITHUB_ENV
          echo "IS_COMMENT=true" >> $GITHUB_ENV
        fi

    - name: Calculate Folder Hash
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/calculate-hash.sh
        bash ${{ github.action_path }}/action-scripts/calculate-hash.sh

    - name: Cache Domloo Dependencies & Dist
      id: domloo-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.action_path }}/node_modules
          ${{ github.action_path }}/dist
        # Sekarang kuncinya beneran akurat ngikutin isi file TS lu!
        key: domloo-build-${{ env.DOMLOO_SRC_HASH }}

    - name: Install & Compile On-the-Fly
      if: steps.domloo-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/install-compile.sh
        bash ${{ github.action_path }}/action-scripts/install-compile.sh

    - name: Jalankan Otak Bot Pinter
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Update File Konfigurasi Projek (SED Engine)
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/action-scripts/sed-engine.sh
        bash ${{ github.action_path }}/action-scripts/sed-engine.sh

    - name: Create Release Branch and Push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/push-engine.js