name: 'Domloo Release Action'
description: 'Smart release automation using custom bot identities'

inputs:
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite" # Ini pembedanya, ngasih tahu GitHub kalau ini composite
  steps:
    - name: Deteksi Trigger
      shell: bash # DI COMPOSITE WAJIB TULIS SHELL DI TIAP STEP RUN
      run: |
        if [ "${{ github.event_name }}" == "issue_comment" ]; then
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "COMMENT_FOUND=$COMMENT_BODY" >> $GITHUB_ENV
          echo "IS_COMMENT=true" >> $GITHUB_ENV
        fi

    - name: Jalankan Otak Bot Pinter
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Update File Konfigurasi Projek (SED Engine)
      if: env.NEW_VERSION != ''
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.NEW_VERSION }}\"/g" package.json
        fi
        if [ -f "Cargo.toml" ]; then
          sed -i "s/^version = \".*\"/version = \"${{ env.NEW_VERSION }}\"/g" Cargo.toml
        fi

    - name: Create Release Branch and Push
      if: env.NEW_VERSION != ''
      shell: bash
      env:
        # TAMBAHKAN BARIS INI: Mengoper variabel dari Runner Env ke Node Process
        NEW_VERSION: ${{ env.NEW_VERSION }}
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
        GH_TOKEN: ${{ inputs.token || github.token }}
      run: node ${{ github.action_path }}/dist/push-engine.js
